language: node_js

node_js:
  - node
  - 10
  - 11

env:
  - workerCount=3

matrix:
  fast_finish: true

install:
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1

script:
  - npm run lint
  # - npm run build
