language: node_js
node_js:
  - 10.11.0
before_install:
- npm --verbose -g i tslint typescript homebridge
script:
- tslint -c ./tslint.json --project .
- tsc
- npm --verbose test
- npm --verbose publish --dry-run
- DEBUG=* timeout -k 20s -s SIGINT 15s homebridge -Q -P ./ -U ./testing-config ; test $? == 124
